name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      maven_goal:
        description: "Maven goal to run"
        required: true
        default: "clean package"
        type: string

      jdk_version:
        description: "JDK version to use"
        required: true
        default: "21"
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}
          cache: maven

      - name: Build Maven project
        run: mvn -B ${{ inputs.maven_goal }} -Dmaven.test.skip=true
